vscode:
  extensions:
    - octref.vetur@0.28.0:bW1RGNnmWYQO43JdJgK34w==
    - formulahendry.auto-close-tag@0.5.9:+RYHu1HN3BGIwbss/7NjBA==
    - steoates.autoimport@1.5.3:Tr3qYUEEq73wrKwCWaYivQ==
    - CoenraadS.bracket-pair-colorizer-2@0.2.0:R8flOpw1fEZe6KyMNNNqBQ==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
    - Gruntfuggly.bettercomment@0.0.10:eqgmN2c/7+QKF81xLdNPTA==